services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - "./volume/:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=example123
      - POSTGRES_USER=administrador
      - POSTGRES_DB=maindb